-- MySQL Script generated by MySQL Workbench
-- qua 11 jun 2025 10:43:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `administrador` TINYINT NOT NULL DEFAULT 0,
  `controlelogin` INT NULL,
  `gerenciapromo` INT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `data` DATE NOT NULL,
  `avaliacao` INT NOT NULL,
  `pagamento` INT NOT NULL,
  `entrega` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `tb_cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_tb_pedido_tb_cliente1_idx` (`tb_cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_tb_cliente1`
    FOREIGN KEY (`tb_cliente_idcliente`)
    REFERENCES `mydb`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_promocao` (
  `idpromocao` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(20) NOT NULL,
  `datainicio` DATE NOT NULL,
  `datafinal` DATE NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`idpromocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbcategoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `preco_venda` VARCHAR(45) NOT NULL,
  `lucro` VARCHAR(45) NOT NULL,
  `tb_promocao_idpromocao` INT NOT NULL,
  `tbcategoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idprodutos`),
  INDEX `fk_tb_produtos_tb_promocao1_idx` (`tb_promocao_idpromocao` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tbcategoria1_idx` (`tbcategoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_promocao1`
    FOREIGN KEY (`tb_promocao_idpromocao`)
    REFERENCES `mydb`.`tb_promocao` (`idpromocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tbcategoria1`
    FOREIGN KEY (`tbcategoria_idcategoria`)
    REFERENCES `mydb`.`tbcategoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_pedido` (
  `iditem_pedido` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tb_pedido_idpedido` INT NOT NULL,
  `tb_produtos_idtb_produtos` INT NOT NULL,
  PRIMARY KEY (`iditem_pedido`, `quantidade`, `preco`),
  INDEX `fk_item_pedido_tb_pedido_idx` (`tb_pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_item_pedido_tb_produtos1_idx` (`tb_produtos_idtb_produtos` ASC) VISIBLE,
  CONSTRAINT `fk_item_pedido_tb_pedido`
    FOREIGN KEY (`tb_pedido_idpedido`)
    REFERENCES `mydb`.`tb_pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_tb_produtos1`
    FOREIGN KEY (`tb_produtos_idtb_produtos`)
    REFERENCES `mydb`.`tb_produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `data` DATE NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL,
  `tb_produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idestoque`),
  INDEX `fk_tb_estoque_tb_produtos1_idx` (`tb_produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_estoque_tb_produtos1`
    FOREIGN KEY (`tb_produtos_idprodutos`)
    REFERENCES `mydb`.`tb_produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NOT NULL,
  `tb_produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_tb_comentario_tb_produtos1_idx` (`tb_produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_comentario_tb_produtos1`
    FOREIGN KEY (`tb_produtos_idprodutos`)
    REFERENCES `mydb`.`tb_produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
